name: Daily

on:
  schedule:
    - cron: '00 2 * * *'  
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyPDF2
    
    - name: Install Ghostscript
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript

    - name: Run script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python script.py
